name: unitask_movil
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  http: ^1.3.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.0.3
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/UTM_Logo.png
